version: "3.8"
services:
  db:
    container_name: blog_db
    image: postgres:15
    restart: always
    command: postgres -c 'max_connections=250'
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
